export enum BentocordVariable {
	BENTOCORD_TOKEN = 'BENTOCORD_TOKEN',
	BENTOCORD_CLIENT_OPTIONS = 'BENTOCORD_CLIENT_OPTIONS',

	BENTOCORD_COMMAND_PREFIX = 'BENTOCORD_COMMAND_PREFIX',
	BENTOCORD_BUILTIN_COMMANDS = 'BENTOCORD_BUILTIN_COMMANDS',

	BENTOCORD_BOT_OWNERS = 'BENTOCORD_BOT_OWNERS',
	BENTOCORD_TEST_GUILDS = 'BENTOCORD_TEST_GUILDS',
}
