export enum BentocordVariable {
	BENTOCORD_TOKEN = 'BENTOCORD_TOKEN',
	BENTOCORD_APPLICATION_ID = 'BENTOCORD_APPLICATION_ID',

	BENTOCORD_DEBUG_GUILDS = 'BENTOCORD_DEBUG_GUILDS',

	BENTOCORD_COMMAND_PREFIX = 'BENTOCORD_COMMAND_PREFIX',
	BENTOCORD_BUILTIN_COMMANDS = 'BENTOCORD_BUILTIN_COMMANDS',

	BENTOCORD_CLIENT_OPTIONS = 'BENTOCORD_CLIENT_OPTIONS',

	BENTOCORD_BOT_OWNERS = 'BENTOCORD_BOT_OWNERS',
}
